# Generated by Django 6.1.1 on 2026-09-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('roll_number', models.CharField(max_length=50)),
                ('semester', models.PositiveSmallIntegerField()),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='exams.course')),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='exams.examsession')),
            ],
            options={
                'indexes': [models.Index(fields=['exam_session', 'course'], name='students_st_exam_se_1e1ce0_idx')],
                'unique_together': {('exam_session', 'roll_number')},
            },
        ),
    ]
