# Generated by Django 6.1.1 on 2026-09-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        ('seating', '0001_initial'),
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvigilationAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom')),
                ('seating_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invigilations', to='seating.seatingplan')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher')),
            ],
            options={
                'indexes': [models.Index(fields=['teacher', 'seating_plan'], name='invigilatio_teacher_5b624e_idx')],
                'unique_together': {('seating_plan', 'classroom')},
            },
        ),
    ]
