# Generated by Django 6.1.1 on 2026-09-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LayoutType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('shape', models.CharField(choices=[('grid', 'Grid'), ('circular', 'Circular')], max_length=10)),
                ('rows', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('cols', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seat_count', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seat_numbering_format', models.CharField(default='A1', help_text="'A1' for row-letter+col-number, 'R1C1' for row-col numeric", max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('layout_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='classrooms.layouttype')),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('row', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('col', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('index', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('layout_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='classrooms.layouttype')),
            ],
            options={
                'ordering': ['row', 'col', 'index'],
                'unique_together': {('layout_type', 'label')},
            },
        ),
        migrations.CreateModel(
            name='SeatAdjacency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjacent_seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='classrooms.seat')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjacencies', to='classrooms.seat')),
            ],
            options={
                'unique_together': {('seat', 'adjacent_seat')},
            },
        ),
    ]
