# Generated by Django 6.1.1 on 2026-09-11 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('semester', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('duty_gap_slots', models.PositiveSmallIntegerField(default=1, help_text="Minimum number of slots between a teacher's consecutive duties")),
                ('daily_duty_cap', models.PositiveSmallIntegerField(default=2, help_text='Max duties per teacher per day in this session')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="e.g. 'Morning', 'Afternoon'", max_length=50)),
                ('start_time', models.TimeField()),
                ('duration_minutes', models.PositiveSmallIntegerField()),
                ('order_index', models.PositiveSmallIntegerField(default=0)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='exams.examsession')),
            ],
            options={
                'ordering': ['exam_session', 'order_index'],
            },
        ),
        migrations.CreateModel(
            name='SlotCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_students', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_courses', to='exams.course')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_courses', to='exams.slot')),
            ],
            options={
                'unique_together': {('slot', 'course')},
            },
        ),
        migrations.AddField(
            model_name='slot',
            name='courses',
            field=models.ManyToManyField(related_name='slots', through='exams.SlotCourse', to='exams.course'),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('exam_session', 'order_index')},
        ),
    ]
