# Generated by Django 6.1.1 on 2026-09-11 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_type', models.CharField(choices=[('seating_gen', 'Seating Generation'), ('pdf_gen', 'PDF Generation'), ('excel_parse', 'Excel Parse'), ('email_batch', 'Email Batch')], max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('done', 'Done'), ('failed', 'Failed')], default='queued', max_length=10)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('progress_pct', models.PositiveSmallIntegerField(default=0)),
                ('progress_label', models.CharField(blank=True, max_length=255)),
                ('result_ref', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
