# Generated by Django 6.1.1 on 2026-09-11 09:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classrooms', '0001_initial'),
        ('exams', '0001_initial'),
        ('jobs', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SeatingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('preview', 'Preview'), ('approved', 'Approved')], default='draft', max_length=10)),
                ('conflict_count', models.PositiveIntegerField(default=0)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_conflicts', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_plans', to=settings.AUTH_USER_MODEL)),
                ('exam_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_plans', to='exams.examsession')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_plans', to=settings.AUTH_USER_MODEL)),
                ('job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seating_plan', to='jobs.job')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seating_plans', to='exams.slot')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('exam_session', 'slot', 'version')},
            },
        ),
        migrations.CreateModel(
            name='SeatAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_conflict', models.BooleanField(default=False)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.classroom')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classrooms.seat')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('seating_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='seating.seatingplan')),
            ],
            options={
                'indexes': [models.Index(fields=['seating_plan', 'classroom'], name='seating_sea_seating_ae8ccc_idx')],
                'unique_together': {('seating_plan', 'classroom', 'seat')},
            },
        ),
    ]
